"""add migration logging

Revision ID: f6235a2696a4
Revises: 
Create Date: 2026-03-02 16:22:28.523221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6235a2696a4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA internal")
    op.create_table('migration_log',
    sa.Column('migration_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('revision', sa.String(length=50), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('info', sa.String(), server_default=sa.text("'No more info included'"), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('migration_id'),
    schema='internal'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('migration_log', schema='internal')
    op.execute("DROP SCHEMA internal")
    # ### end Alembic commands ###